name: Vercel Production Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Pull Vercel config
        run: pnpm dlx vercel@latest pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build for production
        run: pnpm dlx vercel@latest build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel (production)
        run: pnpm dlx vercel@latest deploy --prebuilt --prod --token=$VERCEL_TOKEN
